model_param:
    batch_size: 64
    vocab_size: 40000
    num_layers: 1
    layer_size: 4096
    projection: 2048
    seq_len: 10
    num_gates: 4
    num_non_linear: 5
    num_add: 8
    data_scale: 100 

sw_param:
    kernel_launch_overhead: 9e-6 #9us
    precision: 2 

tech_param:
    core:
        nominal_power_per_mcu: 0.37 #W
        nominal_flop_rate_per_mcu: 64
        nominal_area_per_mcu: 1.5 #mm^2
        nominal_frequency: 1.067e9 #Hz
        nominal_voltage: 1.0 
        threshold_voltage: 0.3 
        margin_voltage: 0.35
        operating_area_per_mcu: 1.5 #!!!!operating_area n nominal_area should chnage hand-in-hand as they affect area scaling
        num_mcu_per_bundle: 4 #a bundle can be thought of as an SM, number of tensorcores per SM
        FMA_width: 4            #tensorcore width
        dataflow: "best"        #{wst. ast, ost, best, none}: wst: weight stationary, ast: activation stationary, ost: output stationary
        util: 0.85 #util should be 0.75 (12/16) for tensorcore
    DRAM:
        dynamic_energy_per_bit: 14e-12 #Joules
        static_power_per_bit: 0.6e-12
        area_per_bit: 11e-10 #mm2
        stack_capacity: 1 GB
        area_per_stack: 100 #mm2
        latency: 100e-9
        mem_ctrl_area: 5 #mm2 
        nominal_frequency: 7e9
        nominal_voltage: 1.35 
        threshold_voltage: 0.4 
        margin_voltage: 0.6
        max_voltage: 1.5
        num_links_per_mm: 8
        num_links_per_stack: 32
        util: 1
    SRAM-L2:
        dynamic_energy_per_bit: 260e-15
        static_power_per_bit: 12e-12
        area_per_bit: 24e-8 #mm2
        bank_capacity: 32 KB
        controller_area_per_link: 0.016 #mm2 
        controller_power_per_link: 0.16 #W
        latency: 0
        overhead: 0.20 #20% circuitry overhead in cell area
        util: 0.45
    SRAM-L1:
        dynamic_energy_per_bit: 260e-15
        static_power_per_bit: 18e-12
        area_per_bit: 17e-8 #mm2
        bank_capacity: 2 KB
        controller_area_per_link: 0.002 #mm2 
        controller_power_per_link: 0.02 #W
        latency: 0
        overhead: 0.20
        util: 1
    SRAM-R:
        dynamic_energy_per_bit: 220e-15
        static_power_per_bit: 18e-12
        area_per_bit: 32e-8 #mm2
        bank_capacity: 16 KB
        controller_area_per_link: 0.00 #mm2 
        controller_power_per_link: 0.0 #W
        latency: 0
        overhead: 0.25
        util: 1 
    network:
        intra_node:
          latency: 5e-6 
          nominal_frequency: 3e9
          nominal_voltage: 1
          nominal_energy_per_link: 1e-12
          nominal_area_per_link: 100e-6 #mm^2
          num_links_per_mm: 400
          threshold_voltage: 0.25
          margin_voltage: 0.45
          util: 1
        inter_node:
          latency: 5e-6
          nominal_frequency: 20e9
          nominal_voltage: 1.2
          nominal_energy_per_link: 13e-12
          nominal_area_per_link: 0.045
          num_links_per_mm: 20 #Assuming 4 layers on PCB and 200 um pitch for high speed signalling
          threshold_voltage: 0.35
          margin_voltage: 0.5
          util: 0.96
area_breakdown:
    node_area_budget: 1150 #mm2
    proc_chip_area_budget: 314 #mm2
    core: 0.384
    L2: 0.0815
    L1: 0.133
    reg_mem: 0.0571
    DRAM: 0.14
    network:
      intra_node: 0.0
      inter_node: 0.1

power_breakdown:
    TDP: 75
    core: 0.38 
    DRAM: 0.24
    L2: 0.03
    L1: 0.15
    reg_mem: 0.195
    network:
      intra_node: 0.0
      inter_node: 0.0

perimeter_breakdown:
    DRAM: 0.7
    intra_node: 0.0
    inter_node: 0.5

system_hierarchy:
    num_nodes_per_wafer: 1
    num_workers: 1
    inter_derate: 1
    intra_derate: 0
    kp1_inter: False
    kp2_inter: False
    dp_inter: False
    lp_inter: False

network_topology:
    inter_wafer: "hic" #mesh, torus, crossbar, custom, hierarchical
    intra_wafer: "none"

memory_hierarchy:
    l0: #Register Memory
      type: "SRAM-R"
      scope: "mcu"
    l1: #Shared Memory
      type: "SRAM-L1"
      scope: "mcu-bundle"
    l2: #L2 
      type: "SRAM-L2"
      scope: "global"
    l3: #Global Memory
      type: "DRAM"
      scope: "global" 

scheduling_param:
    auto: False 
    dp: 1
    lp: 1
    kp_hidden_dim1: 1
    kp_hidden_dim2: 1
    kp_softmax_dim1: 1
    kp_softmax_dim2: 1
    kp_embedding_dim1: 1
    kp_embedding_dim2: 1
    kp_projection_dim1: 1
    kp_projection_dim2: 1
    kp_hidden_type: -1
    kp_softmax_type: -1
    kp_embedding_type: -1
    kp_projection_type: -1
